services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
          ignore:
            - node-modules/
        - action: rebuild
          path: package.json
